In [3]:
#建立list
a = [1,3,5,7,9]
a * 2

b = [2, 4, 6, 8, 10]
a + b

result = []
for i in range(5): #跑迴圈，再append
    result.append(a[i]+ b[i])

result    

[3, 7, 11, 15, 19]

In [3]:
import numpy as np

#透過list 建立ndArray 陣列運算

a_array = np.array([1,3,5,7,9])
a_array * 2

b_array = np.array([2, 4, 6, 8, 10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [5]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50, 100) for _ in range(5)]


[66, 66, 92, 89, 90]

In [6]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50, high=100, size=5)

array([73, 67, 56, 85, 50])

In [7]:
np.random.randint(50, high=100, size=(50, 5))


array([[93, 72, 91, 84, 90],
       [68, 81, 91, 90, 92],
       [64, 60, 61, 57, 73],
       [92, 58, 98, 69, 84],
       [50, 90, 66, 79, 59],
       [52, 67, 57, 79, 56],
       [75, 53, 92, 53, 80],
       [56, 52, 84, 81, 66],
       [60, 81, 86, 68, 90],
       [51, 99, 98, 76, 67],
       [80, 68, 64, 55, 64],
       [79, 65, 56, 69, 60],
       [75, 55, 63, 77, 59],
       [96, 88, 85, 59, 99],
       [78, 61, 89, 81, 83],
       [80, 55, 81, 82, 58],
       [64, 90, 75, 83, 50],
       [82, 78, 93, 83, 77],
       [60, 90, 89, 70, 93],
       [72, 82, 59, 57, 57],
       [66, 89, 50, 97, 79],
       [74, 66, 78, 78, 59],
       [68, 74, 75, 99, 80],
       [73, 93, 78, 75, 63],
       [79, 54, 70, 81, 79],
       [50, 79, 81, 95, 77],
       [72, 85, 88, 76, 60],
       [51, 53, 73, 50, 95],
       [90, 98, 84, 98, 72],
       [60, 81, 74, 87, 72],
       [59, 80, 93, 77, 77],
       [99, 69, 85, 53, 90],
       [90, 74, 70, 57, 57],
       [62, 81, 67, 50, 86],
       [91, 69